title: Laurentiu Stamate – A cleaner code reflects a clearer mind
email: laurentiu.stamate@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laurentiustamate94.github.io" # the base hostname & protocol for your site

# Social
githubUsername: laurentiustamate94
twitterUsername: laurentiu2811
dribbbleUsername:
codepenUsername:

# Build settings
plugins:
  - jekyll-paginate

# pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

themeColor: purple # green, blue, orange, purple, grey
fixedNav: 'false' # true or false

permalink: /:categories/:title/index.html
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

# Markdown settings
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style